# Generated by Django 2.0.3 on 2018-05-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment_str', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('pos_votes', models.IntegerField(default=0)),
                ('neg_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='productimages',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='myapp.Products'),
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='myapp.Products'),
        ),
        migrations.AddField(
            model_name='comments',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='myapp.Products'),
        ),
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together={('pid', 'image_url')},
        ),
        migrations.AlterUniqueTogether(
            name='productfeatures',
            unique_together={('pid', 'feature')},
        ),
    ]
